
services:
  app:
    build: .
    container_name: parse_app
    depends_on:
      - db
    env_file:
      - .env 
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    volumes:
      - .:/app
    command: ["python", "app.py"]
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: parse_postgres_db
    restart: always
    environment:
      POSTGRES_USER: em3_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: em_3
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
